// Generated by Wrangler on Mon Aug 12 2024 15:43:32 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
	TWITCH_WEBHOOK_SECRET: string;
	FIREBASE_AUTH: string;
	FIREBASE_PROJECT_ID: string;
	FIREBASE_BASE_URL: string;
}
