// Generated by Wrangler on Mon Aug 12 2024 15:43:32 GMT+0100 (British Summer Time)
// by running `wrangler types`

interface Env {
	TWITCH_WEBHOOK_SECRET: string;
	TWITCH_CLIENT_ID: string;
	TWITCH_USER_AUTH: string;
	TWITCH_BOT_USERNAME: string;
	TWITCH_BOT_ID: string;
	DISCORD_PUBLIC_KEY: string;
	FIREBASE_CREDS: string;
	FIREBASE_PROJECT_ID: string;
	FIREBASE_BASE_URL: string;
}
