name: Compile Rust

on:
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Restore Rust Builds
      uses: actions/cache@v4
      id: restore-rust-binary
      with:
        path: |
          chatdownloader/target
        key: ${{ runner.os }}-rust-binary-${{ hashFiles('chatdownloader/Cargo.toml', 'chatdownloader/Cargo.lock') }}

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Build Release
      working-directory: chatdownloader/
      run: cargo build --release
